# Generated by Django 3.1.5 on 2021-05-31 06:17

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deneme', '0002_auto_20210531_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='articlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='articles_images')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
                ('edit_Date', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('categories', models.ManyToManyField(related_name='article', to='deneme.categoryModel')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'Articles',
                'db_table': 'Article',
            },
        ),
    ]
