# Generated by Django 3.1.5 on 2021-05-31 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0003_articlesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
