# Generated by Django 3.1.5 on 2021-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0005_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('name_lastname', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
                ('edit_Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts     ',
                'db_table': 'contact',
            },
        ),
    ]
