from .contact import contact
from .anasayfa import anasayfa
from .category import category
from .myarticles import myarticles
from .description import description
from .addArticle import addArticle
from .editArticle import editArticle
from .deleteArticle import deleteArticle
from .deleteComment import deleteComment