from .contact import contactView
from .anasayfa import anasayfa
from .category import categoryView
from .myarticles import myarticles
from .description import Description
from .addArticle import addArticleView
from .editArticle import editArticleView
from .deleteArticle import deleteArticleView
from .deleteComment import deleteComment